In [1]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)
print(np.__version__)

2.0.1
1.24.3


In [3]:
arr1 = np.array([[1,2,3],[2,3,4]]) # array function => return ndarray
print(type(arr1))
print(arr1.shape) # 구조 2(row),3(col)
print(arr1.ndim) # 차원

<class 'numpy.ndarray'>
(2, 3)
2


In [4]:
list1 = [1,2,3]
print(type(list1))
arr1 = np.array(list1)
print(type(arr1))
print(arr1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int32


In [5]:
list2 = [1,2,'test']
arr2 = np.array(list2) # => ndarray object
print(arr2)
print(arr2.dtype)

['1' '2' 'test']
<U11


In [6]:
list3 = [1,2,3.0]
arr3 = np.array(list3)
print(arr3)

[1. 2. 3.]


In [7]:
# 강제 형변환 : astype() method (ndarray)
arr_int = np.array([1,2,3])
print(arr_int.dtype)
arr_float = arr_int.astype('float64')
print(arr_int.dtype, arr_float.dtype)
arr_int8 = arr_float.astype('int8')
print(arr_int8.dtype)

int32
int32 float64
int8


In [8]:
# reshape
arr1 = np.arange(10)
print(arr1, arr1.shape, arr1.ndim)

[0 1 2 3 4 5 6 7 8 9] (10,) 1


In [9]:
arr2 = arr1.reshape(2,5)
print(arr2, arr2.shape, arr2.ndim)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5) 2


In [10]:
arr3 = arr1.reshape(5,2)
print(arr3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
arr1 = np.arange(1200)
arr2 = arr1.reshape(-1,50) # 30개 컬럼 고정  행변환 , 2차원 변환
arr3 = arr1.reshape(30,-1) # 행 30개 고정 컬럼 , 2차원 변환 
print(arr2.shape, arr3.shape)

(24, 50) (30, 40)


In [12]:
arr1 = np.arange(8)
print(arr1)

[0 1 2 3 4 5 6 7]


In [13]:
arr3d = arr1.reshape((2,2,2)) # (2,2,2) => tuple   / 2,2,2 => 가변 인자 
print(arr3d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
# 3차원 데이터를 2차원 변경
print(arr3d) 
arr5 = arr3d.reshape(-1,1) # -1,1(컬럼 1개 )
print(arr5.tolist()) # tolist() method => list 변환
# list : 아무거나 다 저장, 반복시 for 사용, 비연속 공간 저장 가능 
# ndarray : 동일 타입 저장 가능, 브로드 캐스팅(랙 X 반복 가능), 연속 공간 저장, 고속 처리 가능

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]


In [15]:
# 인덱싱
arr1 = np.arange(start=1, stop=10)
arr1, type(arr1[3]), arr1[-1]

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.int32, 9)

In [16]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# 5보다 큰 값 추출 
arr1 > 5 

array([False, False, False, False, False,  True,  True,  True,  True])

In [18]:
arr1[[0,-1]]

array([1, 9])

In [19]:
arr1[[True, False, False, False, False, False, False, False, True]]

array([1, 9])

In [20]:
arr1[arr1  > 5]

array([6, 7, 8, 9])

In [21]:
# 1등 학생 이름 추출 : name_arr 사용 
name_arr = np.array(['John','Mike','Sarah','Kate','Kain'])
score_arr = np.array([78,95,84,98,88]) # 기준 : 정렬 
sort_idx = np.argsort(score_arr)[::-1] # DESC
print(sort_idx)
print(name_arr[sort_idx])

[3 1 4 2 0]
['Kate' 'Mike' 'Kain' 'Sarah' 'John']


In [23]:
titanic_df = pd.read_csv('/big16/python_dev/titanic/data/train.csv')
indexes = titanic_df.index

In [25]:
print (indexes)

RangeIndex(start=0, stop=891, step=1)


In [27]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n', (series_fair + 3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [28]:
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_drop_df.head(3)

NameError: name 'titanic_drop_df' is not defined